server:
  port: 9000
spring:
#  kafka:
#    consumer:
#      bootstrap-servers: localhost:9092
#      group-id: group_id
#      auto-offset-reset: latest
##      auto-offset-reset: earliest  starts from all that not commited
#      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      enable-auto-commit: true
#
#    producer:
#      bootstrap-servers: localhost:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#

  datasource:
    driver-class-name:  oracle.jdbc.OracleDriver
    username: kafka
    password: 123
    url: jdbc:oracle:thin:@192.168.64.12:1521:XE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle12cDialect
    database: oracle
